"""add urgencia field to solicitud

Revision ID: 55772c6b68ce
Revises: a32997d10b1e
Create Date: 2025-11-14 09:51:56.426411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55772c6b68ce'
down_revision: Union[str, None] = 'a32997d10b1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitudes', sa.Column('urgencia', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solicitudes', 'urgencia')
    # ### end Alembic commands ###
