"""Add EnvioTracking model and EstadoEnvio enum

Revision ID: a32997d10b1e
Revises: fef61ec919d5
Create Date: 2025-11-11 17:50:43.504515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a32997d10b1e'
down_revision: Union[str, None] = 'fef61ec919d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('envios_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_compra_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_TRANSITO', 'EN_ADUANA', 'EN_DISTRIBUCION', 'EN_ENTREGA', 'ENTREGADO', 'DEVUELTO', 'CANCELADO', name='estadoenvio'), nullable=False),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('proveedor_envio', sa.String(length=100), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('fecha_entrega_estimada', sa.DateTime(), nullable=True),
    sa.Column('fecha_entrega_real', sa.DateTime(), nullable=True),
    sa.Column('ubicacion_actual', sa.String(length=300), nullable=True),
    sa.Column('ciudad_origen', sa.String(length=100), nullable=True),
    sa.Column('ciudad_destino', sa.String(length=100), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('eventos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['orden_compra_id'], ['ordenes_compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_envios_tracking_estado'), 'envios_tracking', ['estado'], unique=False)
    op.create_index(op.f('ix_envios_tracking_id'), 'envios_tracking', ['id'], unique=False)
    op.create_index(op.f('ix_envios_tracking_orden_compra_id'), 'envios_tracking', ['orden_compra_id'], unique=True)
    op.create_index(op.f('ix_envios_tracking_tracking_number'), 'envios_tracking', ['tracking_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_envios_tracking_tracking_number'), table_name='envios_tracking')
    op.drop_index(op.f('ix_envios_tracking_orden_compra_id'), table_name='envios_tracking')
    op.drop_index(op.f('ix_envios_tracking_id'), table_name='envios_tracking')
    op.drop_index(op.f('ix_envios_tracking_estado'), table_name='envios_tracking')
    op.drop_table('envios_tracking')
    # ### end Alembic commands ###
