"""Initial migration: create all tables

Revision ID: fef61ec919d5
Revises: 
Create Date: 2025-11-06 22:01:48.310350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fef61ec919d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=True),
    sa.Column('rut', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=False),
    sa.Column('sitio_web', sa.String(length=300), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('subcategorias', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('es_verificado', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveedores_categoria'), 'proveedores', ['categoria'], unique=False)
    op.create_index(op.f('ix_proveedores_ciudad'), 'proveedores', ['ciudad'], unique=False)
    op.create_index(op.f('ix_proveedores_email'), 'proveedores', ['email'], unique=False)
    op.create_index(op.f('ix_proveedores_id'), 'proveedores', ['id'], unique=False)
    op.create_index(op.f('ix_proveedores_nombre'), 'proveedores', ['nombre'], unique=False)
    op.create_index(op.f('ix_proveedores_rut'), 'proveedores', ['rut'], unique=True)
    op.create_table('solicitudes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.String(length=100), nullable=True),
    sa.Column('usuario_nombre', sa.String(length=200), nullable=False),
    sa.Column('usuario_contacto', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('cantidad', sa.String(length=100), nullable=True),
    sa.Column('presupuesto', sa.Float(), nullable=True),
    sa.Column('fecha_limite', sa.DateTime(), nullable=True),
    sa.Column('prioridad', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_PROCESO', 'COTIZACIONES_RECIBIDAS', 'APROBADA', 'COMPLETADA', 'CANCELADA', name='estadosolicitud'), nullable=False),
    sa.Column('notas_internas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_categoria'), 'solicitudes', ['categoria'], unique=False)
    op.create_index(op.f('ix_solicitudes_estado'), 'solicitudes', ['estado'], unique=False)
    op.create_index(op.f('ix_solicitudes_id'), 'solicitudes', ['id'], unique=False)
    op.create_index(op.f('ix_solicitudes_usuario_id'), 'solicitudes', ['usuario_id'], unique=False)
    op.create_table('rfqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('numero_rfq', sa.String(length=50), nullable=False),
    sa.Column('asunto', sa.String(length=300), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'ENVIADO', 'RESPONDIDO', 'IGNORADO', 'EXPIRADO', name='estadorfq'), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('fecha_respuesta', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfqs_estado'), 'rfqs', ['estado'], unique=False)
    op.create_index(op.f('ix_rfqs_id'), 'rfqs', ['id'], unique=False)
    op.create_index(op.f('ix_rfqs_numero_rfq'), 'rfqs', ['numero_rfq'], unique=True)
    op.create_index(op.f('ix_rfqs_proveedor_id'), 'rfqs', ['proveedor_id'], unique=False)
    op.create_index(op.f('ix_rfqs_solicitud_id'), 'rfqs', ['solicitud_id'], unique=False)
    op.create_table('cotizaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfq_id', sa.Integer(), nullable=False),
    sa.Column('precio_total', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=False),
    sa.Column('tiempo_entrega', sa.Integer(), nullable=True),
    sa.Column('condiciones_pago', sa.String(length=300), nullable=True),
    sa.Column('garantia', sa.String(length=300), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('archivo_adjunto', sa.String(length=500), nullable=True),
    sa.Column('archivo_nombre', sa.String(length=200), nullable=True),
    sa.Column('es_valida', sa.Boolean(), nullable=False),
    sa.Column('puntaje_ia', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cotizaciones_id'), 'cotizaciones', ['id'], unique=False)
    op.create_index(op.f('ix_cotizaciones_rfq_id'), 'cotizaciones', ['rfq_id'], unique=False)
    op.create_table('ordenes_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('cotizacion_id', sa.Integer(), nullable=False),
    sa.Column('numero_orden', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'ENVIADA', 'CONFIRMADA', 'EN_PROCESO', 'COMPLETADA', 'CANCELADA', name='estadoordencompra'), nullable=False),
    sa.Column('monto_total', sa.Float(), nullable=False),
    sa.Column('moneda', sa.String(length=10), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), nullable=True),
    sa.Column('fecha_entrega_esperada', sa.DateTime(), nullable=True),
    sa.Column('fecha_entrega_real', sa.DateTime(), nullable=True),
    sa.Column('condiciones', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('archivo_oc', sa.String(length=500), nullable=True),
    sa.Column('aprobado_por', sa.String(length=200), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordenes_compra_cotizacion_id'), 'ordenes_compra', ['cotizacion_id'], unique=False)
    op.create_index(op.f('ix_ordenes_compra_estado'), 'ordenes_compra', ['estado'], unique=False)
    op.create_index(op.f('ix_ordenes_compra_id'), 'ordenes_compra', ['id'], unique=False)
    op.create_index(op.f('ix_ordenes_compra_numero_orden'), 'ordenes_compra', ['numero_orden'], unique=True)
    op.create_index(op.f('ix_ordenes_compra_solicitud_id'), 'ordenes_compra', ['solicitud_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ordenes_compra_solicitud_id'), table_name='ordenes_compra')
    op.drop_index(op.f('ix_ordenes_compra_numero_orden'), table_name='ordenes_compra')
    op.drop_index(op.f('ix_ordenes_compra_id'), table_name='ordenes_compra')
    op.drop_index(op.f('ix_ordenes_compra_estado'), table_name='ordenes_compra')
    op.drop_index(op.f('ix_ordenes_compra_cotizacion_id'), table_name='ordenes_compra')
    op.drop_table('ordenes_compra')
    op.drop_index(op.f('ix_cotizaciones_rfq_id'), table_name='cotizaciones')
    op.drop_index(op.f('ix_cotizaciones_id'), table_name='cotizaciones')
    op.drop_table('cotizaciones')
    op.drop_index(op.f('ix_rfqs_solicitud_id'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_proveedor_id'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_numero_rfq'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_id'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_estado'), table_name='rfqs')
    op.drop_table('rfqs')
    op.drop_index(op.f('ix_solicitudes_usuario_id'), table_name='solicitudes')
    op.drop_index(op.f('ix_solicitudes_id'), table_name='solicitudes')
    op.drop_index(op.f('ix_solicitudes_estado'), table_name='solicitudes')
    op.drop_index(op.f('ix_solicitudes_categoria'), table_name='solicitudes')
    op.drop_table('solicitudes')
    op.drop_index(op.f('ix_proveedores_rut'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_nombre'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_id'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_email'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_ciudad'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_categoria'), table_name='proveedores')
    op.drop_table('proveedores')
    # ### end Alembic commands ###
